### ISSUE TITLE
Getting attribute for template returning NoneType

### ISSUE THREAD

**Issue by TheM0ng00se** [RiotGames/cloud-inquisitor#181]
An error may be observed from a worker thread:

Traceback (most recent call last):
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_scheduler_sqs/__init__.py", line 345, in execute_worker
    worker.run()
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_auditor_required_tags/__init__.py", line 115, in run
    self.notify(notifications)
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_auditor_required_tags/__init__.py", line 440, in notify
    body_html = tmpl_html.render(data=data)
  File "/opt/pyenv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/pyenv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pyenv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 114, in top-level template code
  File "/opt/pyenv/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'account'

**Comment by laf-rge** [comment]
we see a lost connection to the database around this time in the logs as well.

**Comment by TheM0ng00se** [comment]
Also seems to follow this error:

cinq_scheduler_sqs Failed processing scheduler job: {"entry_point": {"module_name": "cinq_auditor_required_tags", "name": "auditor_required_tags", "attrs": ["RequiredTagsAuditor"]}, "job_name": "ea1352436c3dbbc9900a48923acd429c3e8ca47a2c033bcc5bd1079dcd72ec32", "batch_id": "6bc71803-0739-45f6-946f-88984ce873c5", "job_id": "c6a76cfd-d75d-4706-b8f7-1a2f9dba9369", "worker_args": {}}
Traceback (most recent call last):
