### ISSUE TITLE
AWS Regional Collector for ELBs not handling existing resources correctly

### ISSUE THREAD

**Issue by TheM0ng00se** [RiotGames/cloud-inquisitor#207]
The regional collector may thrown the following exception. 

[20:26:17] cinq_collector_aws.region There was a problem during ELB collection for riotweb/us-west-2
Traceback (most recent call last):
  File "/opt/cinq/cinq-venv/lib/python3.5/site-packages/cinq_collector_aws/region.py", line 578, in update_elbs
    tags=tags
  File "/opt/cinq/cinq-backend/backend/cloud_inquisitor/plugins/types/resources.py", line 147, in create
    raise ResourceException('Resource {} already exists'.format(resource_id))
cloud_inquisitor.exceptions.ResourceException: Resource us-west-2::<ELB-NAME> already exists

**Comment by TheM0ng00se** [comment]
We aren't actively needing to enforce on xLBs and going forward we will likely move this functionality into AWSConfig.
