### ISSUE TITLE
SQS Scheduler is Getting Duplicate Key Errors

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#47]
This might be related to why I can't get any data back from the workers...

```
mysql> select * from scheduler_batches
    -> ;
+--------------------------------------+--------+---------------------+---------------------+
| batch_id                             | status | started             | completed           |
+--------------------------------------+--------+---------------------+---------------------+
| 94ff94b1-c11f-49b9-a60e-2d73a78564c2 |      2 | 2017-11-28 19:22:07 | 2017-11-28 19:22:41 |
| b7d0055f-81c6-442c-b709-25d6966284ae |      2 | 2017-11-28 19:11:51 | 2017-11-28 19:11:56 |
| bb259db6-965d-4803-bed2-0b6ce081f9cb |      2 | 2017-11-28 19:11:52 | 2017-11-28 19:12:24 |
| ce4d0b95-5d04-49bb-9fb4-7a21ed003558 |      2 | 2017-11-28 19:16:30 | 2017-11-28 19:17:17 |
| de990d23-a9fd-4b15-bc96-bac1f2379904 |      2 | 2017-11-28 19:30:17 | 2017-11-28 19:30:41 |
| e860064d-e4e5-40c8-bebf-e879661f873c |      2 | 2017-11-28 19:36:31 | 2017-11-28 19:37:05 |
| ecd43c41-6e86-4000-a094-240dff07154d |      2 | 2017-11-28 19:26:54 | 2017-11-28 19:27:11 |
| f3e4871f-9619-433d-a602-d07157256357 |      2 | 2017-11-28 19:17:12 | 2017-11-28 19:17:47 |
+--------------------------------------+--------+---------------------+---------------------+
8 rows in set (0.00 sec)

mysql> select * from scheduler_jobs;
+--------------------------------------+--------------------------------------+--------+----------------------------------------+
| job_id                               | batch_id                             | status | data                                   |
+--------------------------------------+--------------------------------------+--------+----------------------------------------+
| 6ab13a9d-a8a1-40f4-947c-563309da48cf | e860064d-e4e5-40c8-bebf-e879661f873c |      2 | {"account": "myaccount"} |
| fd55243e-25b8-46e2-a10e-d159b8f96390 | e860064d-e4e5-40c8-bebf-e879661f873c |      2 | {}                                     |
+--------------------------------------+--------------------------------------+--------+----------------------------------------+
```

```
[19:41:32] cinq_scheduler_sqs [ERROR] Error when processing worker task
Traceback (most recent call last):
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '6ab13a9d-a8a1-40f4-947c-563309da48cf' for key 'PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_scheduler_sqs/__init__.py", line 317, in send_worker_queue_message
    db.session.commit()
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 921, in commit
    self.transaction.commit()
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2192, in flush
    self._flush(objects)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2276, in _flush
    flush_context.execute()
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/pyenv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/pyenv/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.IntegrityError: (_mysql_exceptions.IntegrityError) (1062, "Duplicate entry '6ab13a9d-a8a1-40f4-947c-563309da48cf' for key 'PRIMARY'") [SQL: 'INSERT INTO scheduler_jobs (job_id, batch_id, status, data) VALUES (%s, %s, %s, %s)'] [parameters: ('6ab13a9d-a8a1-40f4-947c-563309da48cf', 'e860064d-e4e5-40c8-bebf-e879661f873c', 0, '{"account": "myaccount"}')]
```

**Comment by tomvachon** [comment]
I also see that on restart via supervisorctl there are many unclear shutdowns in the mysql adapter handler code, this might be related.

On MySQL you see that manifest as communication packet errors and in CINQ you see that manifest as "mysql server has gone away" and occasionally with transaction id reference errors

**Comment by tomvachon** [comment]
Fixed by https://github.com/RiotGames/cinq-scheduler-sqs/pull/1
