### ISSUE TITLE
Unable to locate the SQSScheduler scheduler plugin

### ISSUE THREAD

**Issue by znb** [RiotGames/cloud-inquisitor#54]
I built a Packer AMI using commit: d7f56e30db0bc30c201fd3c3091fdd31a2bab3bb
AMI: ami-996372fd (eu-west-2)

The AMI builds fine and everything appears to be working except for the SQSScheduler:

Output from: /var/log/supervisor/cinq-worker_0-stdout---supervisor-X

`Traceback (most recent call last):
  File "/opt/cinq-backend/manage.py", line 32, in <module>
    manager.run()
  File "/opt/pyenv/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/opt/pyenv/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/opt/pyenv/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/opt/cinq-backend/cloud_inquisitor/plugins/commands/scheduler.py", line 97, in run
    scheduler = self.scheduler_plugins[self.active_scheduler]()
KeyError: 'SQSScheduler'`

Let me know what else you need here.

**Comment by TheM0ng00se** [comment]
yeah the default database config item is set to use SQSScheduler... :(

If you can login through the UI under configuration if you change the value to

StandaloneScheduler

and then restart supervisor you should be good

**Comment by tomvachon** [comment]
Fixed by default changes in #57

**Comment by bunjiboys** [comment]
And mentioned above, this is fixed
