### ISSUE TITLE
Workers timing out under load enumerating snapshots

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cloud-inquisitor#71]
We have ~30 or so accounts in the system.  We are seeing workers timeout pretty regularly on the AWS region collector.  I am seeing it regions across the globe (including the region which the instance lives).  Some of these accounts have a non-trivial amount of snapshots and it seems thats an issue

```
Traceback (most recent call last):
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_scheduler_sqs/__init__.py", line 356, in execute_worker
    worker.run()
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_collector_aws/region.py", line 38, in run
    self.update_snapshots()
  File "/opt/cinq-backend/cloud_inquisitor/wrappers.py", line 54, in __call__
    return self.func(*args, **kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_collector_aws/region.py", line 277, in update_snapshots
    snapshots = {x.id: x for x in ec2.snapshots.filter(OwnerIds=[self.account.account_number])}
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_collector_aws/region.py", line 277, in <dictcomp>
    snapshots = {x.id: x for x in ec2.snapshots.filter(OwnerIds=[self.account.account_number])}
  File "/opt/pyenv/lib/python3.5/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/opt/pyenv/lib/python3.5/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/endpoint.py", line 213, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 605, in send
    r.content
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/vendored/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/vendored/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 450, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/opt/pyenv/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/response.py", line 420, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/lib/python3.5/http/client.py", line 607, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

**Comment by markofu** [comment]
Thanks @tomvachon 

This is a little odd, we're running with 60+ accounts and I don't believe we've seen this.

@bunjiboys have you seen this internally?

**Comment by tomvachon** [comment]
We have thousands of snapshots in these accounts. Some may be north of
10-20k

**Comment by markofu** [comment]
Yeah, I think that’s a greater scale than ours. We will triage it and get
back to you Tom

**Comment by markofu** [comment]
Currently suspect this is related to `boto`. Waiting for feedback from @tomvachon.

**Comment by tomvachon** [comment]
This seems to be resolved by ensuring its on a predictable instance performance type.  I would note that over a scale of say 5 accounts, you need to be on a M or C series in the docs
