### ISSUE TITLE
AttributeError on AWS regional collector when no accounts configured.

### ISSUE THREAD

**Issue by TheM0ng00se** [RiotGames/cloud-inquisitor#92]
The Cinq scheduler will throw AttributeError's on initial config/startup since there are no present active accounts:

```[19:21:22] cinq_scheduler_standalone AWS Region Worker EC2 Region Collector/riotu/us-west-1: 'NoneType' object has no attribute 'account_number'
Traceback (most recent call last):
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_scheduler_standalone/__init__.py", line 247, in execute_aws_region_worker
    worker = cls(**kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_collector_aws/region.py", line 32, in __init__
    self.session = get_aws_session(self.account)
  File "/opt/pyenv/lib/python3.5/site-packages/cloud_inquisitor/__init__.py", line 247, in get_aws_session
    account.account_number,
AttributeError: 'NoneType' object has no attribute 'account_number'
[19:21:22] cinq_scheduler_standalone AWS Region Worker EC2 Region Collector/riotu/ap-northeast-2: 'NoneType' object has no attribute 'account_number'
Traceback (most recent call last):
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_scheduler_standalone/__init__.py", line 247, in execute_aws_region_worker
    worker = cls(**kwargs)
  File "/opt/pyenv/lib/python3.5/site-packages/cinq_collector_aws/region.py", line 32, in __init__
    self.session = get_aws_session(self.account)
  File "/opt/pyenv/lib/python3.5/site-packages/cloud_inquisitor/__init__.py", line 247, in get_aws_session```
    account.account_number,
AttributeError: 'NoneType' object has no attribute 'account_number'

we should be able to account for no accounts or no active accounts.

**Comment by laf-rge** [comment]
This may have been fixed we will attempt to recreate and if we can't we will close this.

**Comment by TheM0ng00se** [comment]
Closing for now.
